### PR TITLE
Update submit app

### PR DESCRIPTION
**Pull request by uclanate**
@krozett can you take a quick look at this? I rearranged the submit new app workflow, and changed the validation for URL and contact name (now not required). I haven't done this yet, but I want to add conditional validation for URL || custom URL scheme || android package name. I had trouble getting the conditional stuff to work so will save that for a later update.

@ctrance can you do a round of testing on submitting an app once Keith merges into master? thanks

### CODE REVIEW

**Comment by ctrance** [comment]
Sure @uclanate , @krozett please let me know when casa staging is updated, thanks!

**Review by krozett — CHANGES_REQUESTED** [review]
It looks like there's a few files you checked in but shouldn't be changed:

- `.ruby-version`
- `Gemfile`
- `Gemfile.lock`
- `config/database.yml` (but we probably should fix those weird IPs and ports at some point)

Otherwise it looks good. If you remove those 4 files from the commit you can go ahead and merge it!

**Comment by uclanate** [comment]
@krozett quick question. what is the best way to remove those 4 files from the commit and recommit? I'm so scared of git right now I really don't want to have to blow away the OPT repo haha

**Comment by uclanate** [comment]
@krozett  OK so it was just the most recent commit where that happened. So I need to "go back" one commit somehow, and then re-add only the correct changes. So should I do the way where you preserve the history or do the force reset thing?

**Comment by uclanate** [comment]
ooo or wait I got it, I'll create a new branch and then we can merge that one.

**Pull request closed without merging**
